# Minimal gitleaks config allowing example env files, scanning everything else
[allowlist]
  description = "Allow common sample files"
  paths = [
    '''(?i)\.env\.example$''',
    '''(?i)\.env\.sample$''',
    '''(?i)sample\.env$''',
    '''(?i)example\.env$''',
  ]