version: '3.9'

# Development convenience override. Run with:
#   docker compose -f docker-compose.yml -f docker-compose.override.yml --profile dev up app-dev redis
# Or bring up Vite dev server as well:
#   docker compose -f docker-compose.yml -f docker-compose.override.yml --profile dev up app-dev vite redis

services:
  app-dev:
    image: node:20-alpine
    profiles: ["dev"]
    working_dir: /app
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - redis
      # - mongo  # enable if using local MongoDB service
    command: >-
      sh -c "apk add --no-cache python3 make g++ && npm install && npm run dev"
    restart: unless-stopped

  vite:
    image: node:20-alpine
    profiles: ["dev"]
    working_dir: /app
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    ports:
      - "5173:5173"
    command: >-
      sh -c "apk add --no-cache python3 make g++ && npm install && npm run dev:frontend"
    restart: unless-stopped

volumes:
  app_node_modules: