name: "Feature Development"
description: "Template for implementing new features with configurable parameters"
version: "1.0.0"
category: "feature-development"

parameters:
  feature_name:
    type: "string"
    required: true
    description: "Name of the feature to implement"
    validation: "^[a-zA-Z0-9_-]+$"
  
  target_directory:
    type: "string" 
    required: false
    default: "src/"
    description: "Target directory for implementation"
  
  priority:
    type: "string"
    required: false
    default: "medium"
    options: ["low", "medium", "high", "critical"]
    description: "Task priority level"
  
  estimated_complexity:
    type: "string"
    required: false
    default: "medium"
    options: ["simple", "medium", "complex", "epic"]
    description: "Estimated complexity of the feature"
    
  requires_testing:
    type: "boolean"
    required: false
    default: true
    description: "Whether automated tests are required"
    
  requires_documentation:
    type: "boolean"
    required: false
    default: true
    description: "Whether documentation updates are required"

triggers:
  - type: "pr_comment"
    pattern: "/implement feature (.+)"
    capture_groups:
      feature_name: 1
  
  - type: "issue_label"
    labels: ["feature-request", "enhancement"]
    
  - type: "manual"
    description: "Manually triggered via API or config"

conditions:
  - name: "target_exists"
    description: "Target directory must exist"
    check: "directory_exists"
    parameter: "{{parameters.target_directory}}"
    
  - name: "no_conflicts"
    description: "No conflicting features in progress"
    check: "no_active_tasks"
    category: "feature-development"
    target: "{{parameters.target_directory}}"

workflow_steps:
  - id: "analyze_requirements"
    name: "Analyze Feature Requirements"
    type: "analysis"
    timeout: "10m"
    inputs:
      feature_name: "{{parameters.feature_name}}"
      target: "{{parameters.target_directory}}"
    outputs:
      - requirements_doc
      - architecture_plan
      - test_strategy
    
  - id: "create_implementation_plan"  
    name: "Create Implementation Plan"
    type: "planning"
    depends_on: ["analyze_requirements"]
    timeout: "5m"
    inputs:
      requirements: "{{steps.analyze_requirements.outputs.requirements_doc}}"
      architecture: "{{steps.analyze_requirements.outputs.architecture_plan}}"
    outputs:
      - implementation_plan
      - file_changes
      
  - id: "implement_feature"
    name: "Implement Feature Code"
    type: "coding"
    depends_on: ["create_implementation_plan"]
    timeout: "30m"
    conditions:
      - "{{conditions.target_exists}}"
      - "{{conditions.no_conflicts}}"
    inputs:
      plan: "{{steps.create_implementation_plan.outputs.implementation_plan}}"
      files: "{{steps.create_implementation_plan.outputs.file_changes}}"
      target_dir: "{{parameters.target_directory}}"
    outputs:
      - code_changes
      - created_files
      - modified_files

success_criteria:
  - name: "implementation_complete"
    check: "step_successful"
    step: "implement_feature"

integrations:
  github_actions:
    - workflow: "enhanced-mcp-phase1.yml"
      trigger_on: ["implement_feature"]
    
  mcp_servers:
    - server: "filesystem"
      operations: ["create_files", "modify_files"]
    - server: "code-sandbox"
      operations: ["validate_code", "run_tests"]