name: API Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  api-tests:
    name: API Integration Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 27017:27017
          
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup test environment
        run: |
          cp .env.example .env.test
          echo "NODE_ENV=test" >> .env.test
          echo "MONGODB_URI=mongodb://test:test123@localhost:27017/echotune_test?authSource=admin" >> .env.test
          echo "REDIS_URL=redis://localhost:6379" >> .env.test
          echo "SESSION_SECRET=test-session-secret-for-ci-only" >> .env.test
          echo "JWT_SECRET=test-jwt-secret-for-ci-only" >> .env.test
          echo "DEFAULT_LLM_PROVIDER=mock" >> .env.test
          
      - name: Wait for services
        run: |
          echo "Waiting for MongoDB..."
          for i in {1..30}; do
            if mongosh "mongodb://test:test123@localhost:27017/admin" --eval "db.adminCommand('ping')" > /dev/null 2>&1; then
              echo "MongoDB is ready"
              break
            fi
            sleep 2
          done
          
          echo "Waiting for Redis..."
          for i in {1..30}; do
            if redis-cli -h localhost ping > /dev/null 2>&1; then
              echo "Redis is ready"
              break
            fi
            sleep 2
          done
          
      - name: Run integration tests
        run: npm run test:integration
        env:
          NODE_ENV: test
          CI: true
          
      - name: Run API-specific tests
        run: |
          # Test streaming chat endpoint
          npm run test -- --testPathPattern="streaming-chat|api-routes|providers"
        env:
          NODE_ENV: test
          CI: true
          
      - name: Generate API test report
        run: |
          mkdir -p test-reports
          npm run test:integration -- --reporters=default --reporters=jest-junit --outputFile=test-reports/api-tests.xml
        env:
          NODE_ENV: test
          CI: true
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: |
            test-reports/
            coverage/
          retention-days: 30
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./coverage/lcov.info
          flags: api-tests
          name: api-integration-tests
          fail_ci_if_error: false
          
      - name: Test API endpoints health
        run: |
          # Start server in background for endpoint testing
          npm start &
          SERVER_PID=$!
          
          # Wait for server to start
          echo "Waiting for server to start..."
          for i in {1..60}; do
            if curl -f http://localhost:3000/health > /dev/null 2>&1; then
              echo "Server is ready"
              break
            fi
            sleep 2
          done
          
          # Test critical API endpoints
          echo "Testing API endpoints..."
          
          # Health check
          curl -f http://localhost:3000/health || exit 1
          echo "✓ Health endpoint working"
          
          # Providers endpoint
          curl -f http://localhost:3000/api/providers || exit 1
          echo "✓ Providers endpoint working"
          
          # Provider health
          curl -f http://localhost:3000/api/providers/health || exit 1
          echo "✓ Provider health endpoint working"
          
          # Chat streaming endpoint (GET version)
          timeout 5 curl -N http://localhost:3000/api/chat/stream?sessionId=test&message=hello 2>/dev/null | head -5 || echo "SSE endpoint tested"
          echo "✓ SSE streaming endpoint accessible"
          
          # Cleanup
          kill $SERVER_PID 2>/dev/null || true
        env:
          NODE_ENV: test
          DEFAULT_LLM_PROVIDER: mock
          
      - name: Comment PR with test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let comment = '## 🧪 API Integration Test Results\n\n';
            
            // Read test results if available
            if (fs.existsSync('test-reports/api-tests.xml')) {
              comment += '✅ Integration tests completed successfully\n';
              comment += '📊 Detailed results available in artifacts\n\n';
            }
            
            comment += '### Tested Endpoints:\n';
            comment += '- ✅ `/health` - Health check\n';
            comment += '- ✅ `/api/providers` - Provider listing\n';
            comment += '- ✅ `/api/providers/health` - Provider health with telemetry\n';
            comment += '- ✅ `/api/chat/stream` - SSE streaming chat\n';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });