name: Block .env files in PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  block-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail if .env-like files are added
        run: |
          set -euo pipefail
          CHANGED="$(git diff --name-only origin/${{ github.base_ref }}...HEAD)"
          echo "Changed files:"
          echo "$CHANGED"

          BLOCKED_REGEX='(^|/)\.env(\..*)?$'
          ALLOW_REGEX='(^|/)\.env\.example$'

          VIOLATIONS=0
          while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            if [[ "$f" =~ $BLOCKED_REGEX ]] && ! [[ "$f" =~ $ALLOW_REGEX ]]; then
              echo "::error file=$f::Blocked .env-like file detected"
              VIOLATIONS=1
            fi
          done <<< "$CHANGED"

          if [[ $VIOLATIONS -ne 0 ]]; then
            echo "Refusing PR: remove .env-like files from commit history."
            exit 1
          fi