---
# Legacy Copilot Models Workflow (Deprecated)
# This workflow has been replaced by gpt5-advanced-multimodel.yml
# Keeping for backward compatibility - redirects to new enhanced workflow

name: GitHub Copilot Models Integration (Legacy)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      model:
        description: 'Copilot model to use (redirected to enhanced workflow)'
        required: true
        default: 'gpt-5'
        type: choice
        options:
          - gpt-5
          - gpt-5-chat
          - gpt-4-turbo
          - gpt-4
      task:
        description: 'Task to perform (redirected to enhanced workflow)'
        required: true
        default: 'analyze'
        type: choice
        options:
          - analyze
          - review
          - document
          - roadmap
          - optimize
          - test

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

jobs:
  redirect-to-enhanced:
    name: "Redirect to Enhanced GPT-5 Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: Post Redirect Notice & Trigger Enhanced Workflow
        uses: actions/github-script@v7
        with:
          script: |
            // Post comment explaining the redirect
            if (context.eventName === 'issue_comment') {
              const comment = `## 🔄 Workflow Redirect Notice
              
              This legacy workflow has been enhanced and moved to **gpt5-advanced-multimodel.yml**.
              
              **Enhanced Features Available:**
              - Advanced GPT-5 model support
              - Unified MCP validation integration
              - Pre-merge validation gating
              - Comprehensive result summaries
              - Multiple trigger types (slash commands, labels, PR events)
              
              **Use These Commands Instead:**
              - \`/gpt5 analyze\` - Full code analysis
              - \`/analyze-gpt5\` - Quick analysis  
              - \`/review-gpt5\` - Code review
              - \`/optimize-gpt5\` - Performance optimization
              
              The enhanced workflow will automatically handle your request with improved capabilities.`;
              
              const contextNumber = context.issue?.number || context.pull_request?.number;
              if (contextNumber) {
                await github.rest.issues.createComment({
                  issue_number: contextNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
              }
            }
            
            // Trigger the enhanced workflow if possible
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'gpt5-advanced-multimodel.yml',
                ref: 'main',
                inputs: {
                  gpt_model: '${{ github.event.inputs.model || "gpt-5" }}',
                  tasks: '${{ github.event.inputs.task || "analyze" }}',
                  target: ''
                }
              });
              console.log('✅ Successfully triggered enhanced GPT-5 workflow');
            } catch (error) {
              console.log('ℹ️ Enhanced workflow trigger skipped:', error.message);
            }