name: History Secret Scan

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run branch and .env scan
        run: |
          bash scripts/security/scan-history.sh

      - name: Gitleaks scan (action)
        uses: zricethezav/gitleaks-action@v2
        with:
          args: "detect --source . --report-format json --report-path exports/security/gitleaks-action.json || true"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: history-secret-scan
          path: exports/security