name: MCP Servers Integration

on:
  workflow_dispatch:
    inputs:
      servers:
        description: 'Comma-separated list of servers to run'
        required: false
        default: 'filesystem,memory,sequential-thinking,github-repos-manager,brave-search,perplexity-mcp,code-sandbox'
      operation:
        description: 'Operation to perform'
        required: true
        default: 'validate'
        type: choice
        options:
          - validate
          - start
          - test
          - health-check

jobs:
  mcp-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm ci
          cd mcp-servers && npm ci
          
      - name: Build MCP Servers
        run: |
          # Build sequential-thinking server
          cd mcp-servers/sequential-thinking && npm install && npm run build
          
      - name: Test Filesystem MCP Server
        if: contains(github.event.inputs.servers, 'filesystem')
        run: node validate-all-mcp-servers.js
        env:


      - name: Test Memory MCP Server
        if: contains(github.event.inputs.servers, 'memory')
        run: node validate-all-mcp-servers.js
        env:


      - name: Test Sequential Thinking Server
        if: contains(github.event.inputs.servers, 'sequential-thinking')
        run: node validate-all-mcp-servers.js
        env:


      - name: Test GitHub Repos Manager MCP
        if: contains(github.event.inputs.servers, 'github-repos-manager')
        run: node validate-all-mcp-servers.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Test Brave Search MCP
        if: contains(github.event.inputs.servers, 'brave-search')
        run: node validate-all-mcp-servers.js
        env:
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}

      - name: Test Perplexity MCP Server
        if: contains(github.event.inputs.servers, 'perplexity-mcp')
        run: node validate-all-mcp-servers.js
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

      - name: Test Code Sandbox Server
        if: contains(github.event.inputs.servers, 'code-sandbox')
        run: node validate-all-mcp-servers.js
        env:


      - name: Generate MCP Status Report
        run: |
          node validate-all-mcp-servers.js > mcp-status.txt
          cat mcp-status.txt
          
      - name: Upload MCP Reports
        uses: actions/upload-artifact@v4
        with:
          name: mcp-validation-reports
          path: |
            mcp-servers-validation-report.json
            MCP_SERVERS_VALIDATION_REPORT.md
            mcp-status.txt

  startup-integration:
    runs-on: ubuntu-latest
    needs: mcp-integration
    if: github.event.inputs.operation == 'start'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Start MCP Orchestrator
        run: |
          timeout 30s npm run mcp-orchestrator || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          
      - name: Test MCP Server Connectivity
        run: |
          # Test individual servers
          timeout 10s npm run mcp:filesystem || echo "Filesystem MCP Server test completed"
          timeout 10s npm run mcp:memory || echo "Memory MCP Server test completed"
          timeout 10s npm run mcp:sequential-thinking || echo "Sequential Thinking Server test completed"
          timeout 10s npm run mcp:github-repos-manager || echo "GitHub Repos Manager MCP test completed"
          timeout 10s npm run mcp:brave-search || echo "Brave Search MCP test completed"
          timeout 10s npm run mcp:perplexity-mcp || echo "Perplexity MCP Server test completed"
          timeout 10s npm run mcp:code-sandbox || echo "Code Sandbox Server test completed"
