name: Roadmap Refresh

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm ci --silent

      - name: Refresh roadmap with Perplexity
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          node scripts/roadmap-refresh.js

      - name: Create Pull Request for roadmap changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(roadmap): auto-refresh roadmap"
          title: "chore(roadmap): auto-refresh roadmap"
          body: "Automated roadmap refresh via workflow"
          branch: automation/roadmap-refresh
          base: main
          add-paths: |
            ROADMAP_AUTO.md
          labels: automation, roadmap