name: Roadmap Refresh

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm ci --silent

      - name: Refresh roadmap with Perplexity
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          node scripts/roadmap-refresh.js

      - name: Commit roadmap if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain ROADMAP_AUTO.md)" ]; then
            git add ROADMAP_AUTO.md
            git commit -m "chore(roadmap): auto-refresh roadmap"
            git push
          else
            echo "No changes to roadmap"
          fi