name: Secrets Inventory (names only)

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "owner/repo to inventory (defaults to this repo)"
        required: false
        type: string

permissions:
  contents: read

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          type -p gh >/dev/null || {
            type -p curl >/dev/null || sudo apt-get install -y curl
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update && sudo apt-get install -y gh
          }

      - name: Run inventory (names only)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/export/github_inventory.sh "${{ inputs.repository || github.repository }}"
          ls -la exports/github || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-inventory
          path: exports/github